// File generated by FlutterFire CLI - DÜZELTİLDİ
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'env.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return web;
      case TargetPlatform.windows:
        throw UnsupportedError('Windows not configured');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux not configured');
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  // DÜZELTME: const KALDIRILDI, Env'e izin vermek için
  static FirebaseOptions get android => FirebaseOptions(
    apiKey: Env.firebaseApiKeyAndroid,
    appId: '1:715610995273:android:a9455e1d89e7324f5a1d98',
    messagingSenderId: '715610995273',
    projectId: 'device-streaming-6f29b03c',
    storageBucket: 'device-streaming-6f29b03c.firebasestorage.app',
  );

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: Env.firebaseApiKeyWeb,
    appId: '1:715610995273:web:9896daeb9a61ce385a1d98',
    messagingSenderId: '715610995273',
    projectId: 'device-streaming-6f29b03c',
    authDomain: 'device-streaming-6f29b03c.firebaseapp.com',
    storageBucket: 'device-streaming-6f29b03c.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: Env.firebaseApiKeyIos,
    appId: '1:715610995273:ios:04d8b52ac3ada20a5a1d98',
    messagingSenderId: '715610995273',
    projectId: 'device-streaming-6f29b03c',
    storageBucket: 'device-streaming-6f29b03c.firebasestorage.app',
    iosBundleId: 'com.ustamgelsin.app.ustamGelsin',
  );
}