// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'env.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => const FirebaseOptions(
    apiKey: Env.firebaseApiKeyAndroid,
    appId: '1:715610995273:android:a9455e1d89e7324f5a1d98',
    messagingSenderId: '715610995273',
    projectId: 'device-streaming-6f29b03c',
    storageBucket: 'device-streaming-6f29b03c.firebasestorage.app',
  );

  static FirebaseOptions get web => const FirebaseOptions(
    apiKey: Env.firebaseApiKeyWeb,
    appId: '1:715610995273:web:9896daeb9a61ce385a1d98',
    messagingSenderId: '715610995273',
    projectId: 'device-streaming-6f29b03c',
    authDomain: 'device-streaming-6f29b03c.firebaseapp.com',
    storageBucket: 'device-streaming-6f29b03c.firebasestorage.app',
  );

  static FirebaseOptions get ios => const FirebaseOptions(
    apiKey: Env.firebaseApiKeyIos,
    appId: '1:715610995273:ios:04d8b52ac3ada20a5a1d98',
    messagingSenderId: '715610995273',
    projectId: 'device-streaming-6f29b03c',
    storageBucket: 'device-streaming-6f29b03c.firebasestorage.app',
    iosBundleId: 'com.ustamgelsin.app.ustamGelsin',
  );
}